spring.profiles.active=local

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


jwt.secret=1234567890987654321234567890987654321
# Час життя токена в мілісекундах 10 годин = 36000000 мс
jwt.expiration=3600000