
spring.datasource.url=jdbc:h2:mem:stg_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=stg_user
spring.datasource.password=stg_pass

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console