# ===============================
# ===============================
server.port=8081
spring.application.name=trainer-workload-service

# ===============================
# Eureka Discovery Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===============================
# MongoDB
# ===============================
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=workload_db

# ===============================
#  ActiveMQ
# ===============================
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false

# ===============================
# ===============================
jwt.secret=RXBhbUd5bUFwcGxpY2F0aW9uU2VjcmV0S2V5VGhhdElzVmVyeVNlY3VyZTIwMjY=